export const experiences = [
    {
      id: 1,
      company: "Turing.com",
      position: "Software Engineer L3",
      duration: "August 2021 - Present",
      description: [
        "Led UI/UX redesign, enhancing the vetting experience for 2.1M users.",
        "Optimized compensation for 70K+ developers through the Rate Refresh Initiative.",
        "Revamped Careers backend and frontend, integrating Greenhouse ATS, reducing HR efforts by 70%.",
        // "Contributed to Trunk-based development adoption for faster and more stable deployments.",
        // "Introduced Cypress tests, achieving 40% end-to-end coverage.",
      ],
      tags: ["React", "Node.js", "AWS", "Cypress", "Docker"],
      location: { coordinates: [-122.4194, 37.7749], city: "San Francisco, USA" },
    },
    {
      id: 2,
      company: "Sixads",
      position: "Senior Software Engineer | Frontend Lead",
      duration: "August 2020 - September 2021",
      description: [
        "Designed and developed front-end systems for 100,000+ Shopify stores.",
        "Led the engineering design and implementation of complex analytics tools, video-ad editors, and dashboards.",
        // "Re-architected old designs into modern, pixel-perfect web designs.",
        "Implemented automated deployment pipelines to Kubernetes via Bitbucket Pipelines.",
      ],
      tags: ["React", "Redux", "Node.js", "Docker", "Kubernetes"],
      location: { coordinates: [25.2797, 54.6872], city: "Vilnius, Lithuania" },
    },
    {
      id: 3,
      company: "Fieldnation",
      position: "Software Engineer",
      duration: "July 2019 - September 2020",
      description: [
        "Developed a robust GET-WORK-DONE system as a full-stack engineer.",
        "Orchestrated complex APIs and microservices, enhancing user experiences.",
        "Created user-centric features with React and Redux, resulting in elevated user engagement.",
        "Guided the team in constructing scalable systems using SOLID principles and message queues.",
      ],
      tags: ["React", "Node.js", "PHP", "AWS", "NestJS"],
      location: { coordinates: [-93.2650, 44.9778], city: "Minneapolis, USA" },
    },
    {
      id: 4,
      company: "Devskill",
      position: "Technical Trainer | Web Development",
      duration: "August 2020 - February 2020",
      description: [
        "Worked as a technical trainer for web development based on PHP, Laravel, and VueJS.",
        "Trained around 30 trainees on API and frontend development.",
      ],
      tags: ["PHP", "Laravel", "Vue.js", "AWS"],
      location: { coordinates: [23.8103, 90.4125], city: "Dhaka, Bangladesh" },
    },
    {
      id: 5,
      company: "Sheba.xyz",
      position: "Software Engineer | Web Team",
      duration: "October 2018 - June 2019",
      description: [
        "Developed APIs for mobile app integration servicing 500K+ users.",
        "Created admin panels and CMS to support 20K+ small entrepreneurs.",
        "Built web front ends for seamless customer experiences.",
      ],
      tags: ["PHP", "Node.js", "MySQL", "MongoDB"],
      location: { coordinates: [23.8103, 90.4125], city: "Dhaka, Bangladesh" },
    },
    {
      id: 6,
      company: "Bytelab Limited",
      position: "Software Developer",
      duration: "August 2017 - September 2018",
      description: [
        "Developed web applications for client solutions using diverse web technology stacks.",
        "Created complex APIs for mobile applications.",
        "Developed hybrid apps using React Native.",
      ],
      tags: ["PHP", "Laravel", "React Native", "MySQL"],
      location: { coordinates: [23.8103, 90.4125], city: "Dhaka, Bangladesh" },
    },
  ];
  